// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Nd1uNQlTmbcTXIt0JomaNlXs4wuaFRc',
    appId: '1:909944335966:web:41af415320513483350ecf',
    messagingSenderId: '909944335966',
    projectId: 'qodo-2223c',
    authDomain: 'qodo-2223c.firebaseapp.com',
    storageBucket: 'qodo-2223c.appspot.com',
    measurementId: 'G-RV4SP59T0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTGLoA5sdiHHtQSZvTVNqWenawp05BtIc',
    appId: '1:909944335966:android:f54aa1115f57c8c6350ecf',
    messagingSenderId: '909944335966',
    projectId: 'qodo-2223c',
    storageBucket: 'qodo-2223c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkzgC9HFa6h7JLgZwCZM_Ag87xpNoRIQU',
    appId: '1:909944335966:ios:e10d862d048ce649350ecf',
    messagingSenderId: '909944335966',
    projectId: 'qodo-2223c',
    storageBucket: 'qodo-2223c.appspot.com',
    iosBundleId: 'com.example.techHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkzgC9HFa6h7JLgZwCZM_Ag87xpNoRIQU',
    appId: '1:909944335966:ios:313bef7856ac15b5350ecf',
    messagingSenderId: '909944335966',
    projectId: 'qodo-2223c',
    storageBucket: 'qodo-2223c.appspot.com',
    iosBundleId: 'com.example.techHabits.RunnerTests',
  );
}
